<?php
// T_OPEN_TAG T_WHITESPACE

// T_WHITESPACE
declare(strict_types=1);
// T_DECLARE T_OPEN_PARENTHESIS T_STRING T_EQUAL T_LNUMBER T_CLOSE_PARENTHESIS T_SEMICOLON T_WHITESPACE

// T_WHITESPACE
namespace PhpCollective;
// T_NAMESPACE T_WHITESPACE T_STRING T_SEMICOLON T_WHITESPACE

// T_WHITESPACE
class ImplicitCastSpacingExample
// T_CLASS T_WHITESPACE T_STRING T_WHITESPACE
{
// T_OPEN_CURLY_BRACKET T_WHITESPACE
    public function run(bool $ready, int $count, int $mask, callable $callable): int
// T_WHITESPACE T_PUBLIC T_WHITESPACE T_FUNCTION T_WHITESPACE T_STRING T_OPEN_PARENTHESIS T_STRING T_WHITESPACE T_VARIABLE T_COMMA T_WHITESPACE T_STRING T_WHITESPACE T_VARIABLE T_COMMA T_WHITESPACE T_STRING T_WHITESPACE T_VARIABLE T_COMMA T_WHITESPACE T_CALLABLE T_WHITESPACE T_VARIABLE T_CLOSE_PARENTHESIS T_COLON T_WHITESPACE T_STRING T_WHITESPACE
    {
// T_WHITESPACE T_OPEN_CURLY_BRACKET T_WHITESPACE
        $not = ! $ready;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_BOOLEAN_NOT T_WHITESPACE T_VARIABLE T_SEMICOLON T_WHITESPACE
        $silenced = @ $callable();
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_ASPERAND T_WHITESPACE T_VARIABLE T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_SEMICOLON T_WHITESPACE
        $negated = - $count;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_MINUS T_WHITESPACE T_VARIABLE T_SEMICOLON T_WHITESPACE

// T_WHITESPACE
        $flipped = ~ $mask;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_BITWISE_NOT T_WHITESPACE T_VARIABLE T_SEMICOLON T_WHITESPACE
        $validNot = !$ready;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_BOOLEAN_NOT T_VARIABLE T_SEMICOLON T_WHITESPACE
        $validSilenced = @$callable();
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_ASPERAND T_VARIABLE T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_SEMICOLON T_WHITESPACE
        $validNegated = -$count;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_MINUS T_VARIABLE T_SEMICOLON T_WHITESPACE
        $validSubtraction = $count - $mask;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_VARIABLE T_WHITESPACE T_MINUS T_WHITESPACE T_VARIABLE T_SEMICOLON T_WHITESPACE
        $constantMinus = __LINE__ - 1;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_LINE T_WHITESPACE T_MINUS T_WHITESPACE T_LNUMBER T_SEMICOLON T_WHITESPACE
        $boolMinus = (int)true - 1;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_INT_CAST T_TRUE T_WHITESPACE T_MINUS T_WHITESPACE T_LNUMBER T_SEMICOLON T_WHITESPACE
        $nullMinus = (int)null - 1;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_INT_CAST T_NULL T_WHITESPACE T_MINUS T_WHITESPACE T_LNUMBER T_SEMICOLON T_WHITESPACE
        $fqcnMinus = \PHP_INT_MAX - 1;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_NAME_FULLY_QUALIFIED T_WHITESPACE T_MINUS T_WHITESPACE T_LNUMBER T_SEMICOLON T_WHITESPACE
        $doubleNegated = - -$count;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_MINUS T_WHITESPACE T_MINUS T_VARIABLE T_SEMICOLON T_WHITESPACE
        $arrow = fn (): int => - $count;
// T_WHITESPACE T_VARIABLE T_WHITESPACE T_EQUAL T_WHITESPACE T_FN T_WHITESPACE T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_COLON T_WHITESPACE T_STRING T_WHITESPACE T_FN_ARROW T_WHITESPACE T_MINUS T_WHITESPACE T_VARIABLE T_SEMICOLON T_WHITESPACE

// T_WHITESPACE
        return (int)$not + (int)$silenced + $negated + $flipped + (int)$validNot
// T_WHITESPACE T_RETURN T_WHITESPACE T_INT_CAST T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_INT_CAST T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_INT_CAST T_VARIABLE T_WHITESPACE
            + (int)$validSilenced + $validNegated + $validSubtraction
// T_WHITESPACE T_PLUS T_WHITESPACE T_INT_CAST T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_VARIABLE T_WHITESPACE
            + $constantMinus + $boolMinus + $nullMinus + $fqcnMinus + $doubleNegated + $arrow();
// T_WHITESPACE T_PLUS T_WHITESPACE T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_VARIABLE T_WHITESPACE T_PLUS T_WHITESPACE T_VARIABLE T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_SEMICOLON T_WHITESPACE
    }
// T_WHITESPACE T_CLOSE_CURLY_BRACKET T_WHITESPACE
}
// T_CLOSE_CURLY_BRACKET T_WHITESPACE