<?php
// T_OPEN_TAG T_WHITESPACE

// T_WHITESPACE
declare(strict_types=1);
// T_DECLARE T_OPEN_PARENTHESIS T_STRING T_EQUAL T_LNUMBER T_CLOSE_PARENTHESIS T_SEMICOLON T_WHITESPACE

// T_WHITESPACE
namespace PhpCollective;
// T_NAMESPACE T_WHITESPACE T_STRING T_SEMICOLON T_WHITESPACE

// T_WHITESPACE
class VoidCastExample
// T_CLASS T_WHITESPACE T_STRING T_WHITESPACE
{
// T_OPEN_CURLY_BRACKET T_WHITESPACE
    public function testVoidCast(): void
// T_WHITESPACE T_PUBLIC T_WHITESPACE T_FUNCTION T_WHITESPACE T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_COLON T_WHITESPACE T_STRING T_WHITESPACE
    {
// T_WHITESPACE T_OPEN_CURLY_BRACKET T_WHITESPACE
        // Correct usage
// T_WHITESPACE T_COMMENT
        (void) $this->methodWithReturn();
// T_WHITESPACE T_OPEN_PARENTHESIS T_STRING T_CLOSE_PARENTHESIS T_WHITESPACE T_VARIABLE T_OBJECT_OPERATOR T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_SEMICOLON T_WHITESPACE

// T_WHITESPACE
        // Missing space after cast
// T_WHITESPACE T_COMMENT
        (void)$this->anotherMethod();
// T_WHITESPACE T_OPEN_PARENTHESIS T_STRING T_CLOSE_PARENTHESIS T_VARIABLE T_OBJECT_OPERATOR T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_SEMICOLON T_WHITESPACE

// T_WHITESPACE
        // Space inside cast
// T_WHITESPACE T_COMMENT
        ( void ) $this->yetAnotherMethod();
// T_WHITESPACE T_OPEN_PARENTHESIS T_WHITESPACE T_STRING T_WHITESPACE T_CLOSE_PARENTHESIS T_WHITESPACE T_VARIABLE T_OBJECT_OPERATOR T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_SEMICOLON T_WHITESPACE

// T_WHITESPACE
        // Extra spaces after cast
// T_WHITESPACE T_COMMENT
        (void)  $this->oneMoreMethod();
// T_WHITESPACE T_OPEN_PARENTHESIS T_STRING T_CLOSE_PARENTHESIS T_WHITESPACE T_VARIABLE T_OBJECT_OPERATOR T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_SEMICOLON T_WHITESPACE

// T_WHITESPACE
        // Combination of issues
// T_WHITESPACE T_COMMENT
        ( void )$this->finalMethod();
// T_WHITESPACE T_OPEN_PARENTHESIS T_WHITESPACE T_STRING T_WHITESPACE T_CLOSE_PARENTHESIS T_VARIABLE T_OBJECT_OPERATOR T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_SEMICOLON T_WHITESPACE
    }
// T_WHITESPACE T_CLOSE_CURLY_BRACKET T_WHITESPACE

// T_WHITESPACE
    private function methodWithReturn(): string
// T_WHITESPACE T_PRIVATE T_WHITESPACE T_FUNCTION T_WHITESPACE T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_COLON T_WHITESPACE T_STRING T_WHITESPACE
    {
// T_WHITESPACE T_OPEN_CURLY_BRACKET T_WHITESPACE
        return 'result';
// T_WHITESPACE T_RETURN T_WHITESPACE T_CONSTANT_ENCAPSED_STRING T_SEMICOLON T_WHITESPACE
    }
// T_WHITESPACE T_CLOSE_CURLY_BRACKET T_WHITESPACE

// T_WHITESPACE
    private function anotherMethod(): int
// T_WHITESPACE T_PRIVATE T_WHITESPACE T_FUNCTION T_WHITESPACE T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_COLON T_WHITESPACE T_STRING T_WHITESPACE
    {
// T_WHITESPACE T_OPEN_CURLY_BRACKET T_WHITESPACE
        return 42;
// T_WHITESPACE T_RETURN T_WHITESPACE T_LNUMBER T_SEMICOLON T_WHITESPACE
    }
// T_WHITESPACE T_CLOSE_CURLY_BRACKET T_WHITESPACE

// T_WHITESPACE
    private function yetAnotherMethod(): bool
// T_WHITESPACE T_PRIVATE T_WHITESPACE T_FUNCTION T_WHITESPACE T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_COLON T_WHITESPACE T_STRING T_WHITESPACE
    {
// T_WHITESPACE T_OPEN_CURLY_BRACKET T_WHITESPACE
        return true;
// T_WHITESPACE T_RETURN T_WHITESPACE T_TRUE T_SEMICOLON T_WHITESPACE
    }
// T_WHITESPACE T_CLOSE_CURLY_BRACKET T_WHITESPACE

// T_WHITESPACE
    private function oneMoreMethod(): array
// T_WHITESPACE T_PRIVATE T_WHITESPACE T_FUNCTION T_WHITESPACE T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_COLON T_WHITESPACE T_STRING T_WHITESPACE
    {
// T_WHITESPACE T_OPEN_CURLY_BRACKET T_WHITESPACE
        return [];
// T_WHITESPACE T_RETURN T_WHITESPACE T_OPEN_SHORT_ARRAY T_CLOSE_SHORT_ARRAY T_SEMICOLON T_WHITESPACE
    }
// T_WHITESPACE T_CLOSE_CURLY_BRACKET T_WHITESPACE

// T_WHITESPACE
    private function finalMethod(): mixed
// T_WHITESPACE T_PRIVATE T_WHITESPACE T_FUNCTION T_WHITESPACE T_STRING T_OPEN_PARENTHESIS T_CLOSE_PARENTHESIS T_COLON T_WHITESPACE T_STRING T_WHITESPACE
    {
// T_WHITESPACE T_OPEN_CURLY_BRACKET T_WHITESPACE
        return null;
// T_WHITESPACE T_RETURN T_WHITESPACE T_NULL T_SEMICOLON T_WHITESPACE
    }
// T_WHITESPACE T_CLOSE_CURLY_BRACKET T_WHITESPACE
}
// T_CLOSE_CURLY_BRACKET T_WHITESPACE